---
- name: Print python version
  debug:
    var: ansible_python

# tasks file for plex
- include: plex.yml

- include: plexpy.yml
  when: plexpy_install

- include: plexupdate.yml
  when: plexupdate_install